### ISSUE TITLE
Vanilla Chat und Systemnachrichten funktionieren nicht

### ISSUE THREAD

**Issue by Floppy012** [RewisServer/RewiMod#63]
Man sieht auf einem Vanilla Server den Chat nicht. Außerdem funktionieren Systemnachrichten wie der Syntax Hinweis auf `/op` oder `/whitelist` nicht.

**Comment by k3kdude** [comment]
In allen Versionen?

**Comment by ComputerBaer** [comment]
Da hast du den Fehler:

```
[23:13:29] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
    at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_101]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_101]
    at tv.rewinside.rewimod.forge.listener.ChatListener.onChatReceive(ChatListener.java:32) ~[ChatListener.class:fbd9b57]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_ChatListener_onChatReceive_ClientChatReceivedEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at net.minecraftforge.event.ForgeEventFactory.onClientChat(ForgeEventFactory.java:272) ~[ForgeEventFactory.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.func_147251_a(NetHandlerPlayClient.java:753) ~[bcy.class:?]
    at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:44) ~[fy.class:?]
    at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:9) ~[fy.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
    ... 9 more
```

**Comment by ComputerBaer** [comment]
Hmm, der Code gefällt mir da allgemein nicht so. Die Erkennung von Spielernamen sollten wir da noch deutlich verbessern. Du kannst das jetzt gerne versuchen, ansonsten setze ich mich da wahrscheinlich morgen dran.

**Comment by k3kdude** [comment]
Mmh, mach du das mal.. habe jetzt auch keine Zeit mehr, außerdem habe ich schon eine offene PR.
